// Generated by CoffeeScript 1.7.1
(function() {
  var Cell, char;

  char = require('./char-query');

  Cell = (function() {
    function Cell() {
      this._dirs = {
        left: 'none',
        up: 'none',
        right: 'none',
        down: 'none'
      };
    }

    Cell.prototype.left = function() {
      if (arguments.length) {
        this._dirs.left = arguments[0];
        return this;
      } else {
        return this._dirs.left;
      }
    };

    Cell.prototype.up = function() {
      if (arguments.length) {
        this._dirs.up = arguments[0];
        return this;
      } else {
        return this._dirs.up;
      }
    };

    Cell.prototype.right = function() {
      if (arguments.length) {
        this._dirs.right = arguments[0];
        return this;
      } else {
        return this._dirs.right;
      }
    };

    Cell.prototype.down = function() {
      if (arguments.length) {
        this._dirs.down = arguments[0];
        return this;
      } else {
        return this._dirs.down;
      }
    };

    Cell.prototype.toString = function() {
      return char({
        left: this.left(),
        up: this.up(),
        right: this.right(),
        down: this.down()
      });
    };

    return Cell;

  })();

  module.exports = function() {
    return new Cell();
  };

}).call(this);
