// Generated by CoffeeScript 1.10.0
(function() {
  var bgize, style;

  style = require('ansi-styles');

  bgize = function(color) {
    return 'bg' + color[0].toUpperCase() + color.slice(1);
  };

  module.exports = {
    foreground: function(color) {
      switch (color) {
        case 'none':
          return style.color.close;
        default:
          if (color in style.color) {
            return style.color[color].open;
          }
      }
      return '';
    },
    background: function(color) {
      var bgColor;
      switch (color) {
        case 'none':
          return style.bgColor.close;
        default:
          bgColor = bgize(color);
          if (bgColor in style.bgColor) {
            return style.bgColor[bgColor].open;
          }
      }
      return '';
    }
  };

}).call(this);
