// Generated by CoffeeScript 1.7.1
(function() {
  var Line;

  Line = (function() {
    function Line() {
      var _ref, _ref1, _ref2;
      if (arguments.length === 1) {
        _ref = arguments[0], this.from = _ref.from, this.to = _ref.to, this.style = _ref.style;
      } else {
        this.from = arguments[0];
        this.to = arguments[1];
        this.style = arguments[2];
      }
      if (!(this instanceof Line)) {
        return new Line({
          from: this.from,
          to: this.to,
          style: this.style
        });
      }
      if (((_ref1 = this.from) != null ? _ref1.length : void 0) !== 2) {
        throw new Error("from coordinates required");
      }
      if (((_ref2 = this.to) != null ? _ref2.length : void 0) !== 2) {
        throw new Error("to coordinates required");
      }
      if (!(this.vertical() || this.horizontal())) {
        throw new Error("coordinates must be collinear");
      }
      if (this.vertical() && this.horizontal()) {
        throw new Error("coordinates must not be coincident");
      }
      if (this.style == null) {
        this.style = "normal";
      }
    }

    Line.prototype.horizontal = function() {
      return this.from[1] === this.to[1];
    };

    Line.prototype.vertical = function() {
      return this.from[0] === this.to[0];
    };

    return Line;

  })();

  module.exports = Line;

}).call(this);
