// Generated by CoffeeScript 1.10.0
(function() {
  var Line;

  Line = (function() {
    function Line() {
      var base, base1, ref, ref1, ref2;
      if (arguments.length === 1) {
        ref = arguments[0], this.from = ref.from, this.to = ref.to, this.style = ref.style, this.color = ref.color;
      } else {
        this.from = arguments[0];
        this.to = arguments[1];
        this.style = arguments[2];
        this.color = {};
        this.color.foreground = arguments[3];
        this.color.background = arguments[4];
      }
      if (!(this instanceof Line)) {
        return new Line({
          from: this.from,
          to: this.to,
          style: this.style,
          color: this.color
        });
      }
      if (((ref1 = this.from) != null ? ref1.length : void 0) !== 2) {
        throw new Error("from coordinates required");
      }
      if (((ref2 = this.to) != null ? ref2.length : void 0) !== 2) {
        throw new Error("to coordinates required");
      }
      if (!(this.vertical() || this.horizontal())) {
        throw new Error("coordinates must be collinear");
      }
      if (this.vertical() && this.horizontal()) {
        throw new Error("coordinates must not be coincident");
      }
      if (this.style == null) {
        this.style = "normal";
      }
      if (this.color == null) {
        this.color = {};
      }
      if ((base = this.color).foreground == null) {
        base.foreground = "none";
      }
      if ((base1 = this.color).background == null) {
        base1.background = "none";
      }
    }

    Line.prototype.horizontal = function() {
      return this.from[1] === this.to[1];
    };

    Line.prototype.vertical = function() {
      return this.from[0] === this.to[0];
    };

    return Line;

  })();

  module.exports = Line;

}).call(this);
