// Generated by CoffeeScript 1.7.1
(function() {
  var Line;

  Line = (function() {
    function Line(_arg) {
      var _ref, _ref1;
      this.from = _arg.from, this.to = _arg.to, this.style = _arg.style;
      if (((_ref = this.from) != null ? _ref.length : void 0) !== 2) {
        throw new Error("from coordinates required");
      }
      if (((_ref1 = this.to) != null ? _ref1.length : void 0) !== 2) {
        throw new Error("to coordinates required");
      }
      if (!(this.vertical() || this.horizontal())) {
        throw new Error("coordinates must be collinear");
      }
      if (this.vertical() && this.horizontal()) {
        throw new Error("coordinates must not be coincident");
      }
      if (this.style == null) {
        this.style = "normal";
      }
    }

    Line.prototype.horizontal = function() {
      return this.from[1] === this.to[1];
    };

    Line.prototype.vertical = function() {
      return this.from[0] === this.to[0];
    };

    return Line;

  })();

  module.exports = function(opts) {
    return new Line(opts || {});
  };

}).call(this);
